server:
  port: 9515
spring:
  application:
    name: microservice-consumer-productservice


logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.aek56.cloud.service.UserServiceFeign: DEBUG


eureka:
  instance:
    hostname: productService
    prefer-ip-address: true
    ip-address: ${eureka.instance.hostname} #只有当prefer-ip-address: true 时才生效
    instance-id: ${eureka.instance.hostname}:${server.port}  # 将Instance ID设置成IP:端口的形式
    status-page-url-path: /productApi      #修改info的地址为API接口页面
    leaseRenewalIntervalInSeconds: 10
    leaseExpirationDurationInSeconds: 30
#    home-page-url-path: /instance-info
  client:
    serviceUrl:
#      defaultZone: http://eadmin:eadmin123@eurekaService1:9511/eureka/,http://eadmin:eadmin123@eurekaService2:9512/eureka/,http://eadmin:eadmin123@eurekaService3:9513/eureka/
      defaultZone: http://ebey.aek56.com:8778/eureka/
    healthcheck:
      enabled: true

